-- GRUPO 3 - HUMISAFE - BEATRIZ RIBEIRO, ISMAEL WECSLEY, KEVIN SILVA, MARCOS HIDEYUKI, PAULO CESAR E PAULO JÚNIOR.

create database humisafe;

use humisafe;

CREATE TABLE sensorDHT11(
idSensor INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
numSerie VARCHAR(100) UNIQUE NOT NULL,
dtFabricacao  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
dtCompra DATETIME NOT NULL,
statusManutencao VARCHAR(10) DEFAULT "Inativo" NOT NULL,
CONSTRAINT checkManutencao CHECK(statusManutencao IN("Ativo","Inativo","Manutencao")),
dtManutencao DATETIME NOT NULL
);

CREATE TABLE umidade(
	idumidade INT PRIMARY KEY AUTO_INCREMENT,
    umidade FLOAT(4,2) NOT NULL,
    dtRegistro DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

